config/routes.rb
Rails.application.routes.draw do
  get 'sessions/create'

  get 'sessions/destroy'

  get 'home/show'
  get 'data', to: 'analytics#data'
  get 'users/:id/edit', to: 'user#edit'
  post 'users/:id/edit', to: 'user#update' 
  get 'account_summaries', to: 'analytics#account_summaries'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get '/check_index' => "google_index#check_index"
  post '/check_index' => "google_index#response_index"
  get '/keywords' => "google_index#index"
  resources :sports

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]

  root to: "home#show"

 get "/koniec-serii" => 'ends#index'
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  get "/codeupdate" => "ends#codeupdate"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/end.rb
class End < ApplicationRecord
end

app/controllers/ends_controller.rb
class EndsController < ApplicationController
  before_action :set_end, only: [:show, :edit, :update, :destroy]
  before_action :require_user

  # GET /ends
  # GET /ends.json
  def index
    @ends = End.all
    #UpdateCodeJob.perform_later
  end
  
  def response_index
     flash[:success] = "#{params[:name]}   #{params[:site_name]}"
     CheckIndexJob.perform_later(params[:name],params[:site_name])
     respond_to do |format|
      format.html { redirect_to root_path }
    end
  end
  
  def check_index
    
  end

  def codeupdate
    UpdateCodeJob.perform_later
    flash[:success] = "Wait 2 minutes and refresh the page"
    respond_to do |format|
      format.html { redirect_to root_path }
    end
  end

  # GET /ends/1
  # GET /ends/1.json
  def show
  end

  # GET /ends/new
  def new
    @end = End.new
  end

  # GET /ends/1/edit
  def edit
  end

  # POST /ends
  # POST /ends.json
  def create
    @end = End.new(end_params)

    respond_to do |format|
      if @end.save
        format.html { redirect_to @end, notice: 'End was successfully created.' }
        format.json { render :show, status: :created, location: @end }
      else
        format.html { render :new }
        format.json { render json: @end.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ends/1
  # PATCH/PUT /ends/1.json
  def update
    respond_to do |format|
      if @end.update(end_params)
        format.html { redirect_to @end, notice: 'End was successfully updated.' }
        format.json { render :show, status: :ok, location: @end }
      else
        format.html { render :edit }
        format.json { render json: @end.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ends/1
  # DELETE /ends/1.json
  def destroy
    @end.destroy
    respond_to do |format|
      format.html { redirect_to ends_url, notice: 'End was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_end
      @end = End.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def end_params
      params.require(:end).permit(:product_id, :product_page, :position)
    end
    
end

app/helpers/ends_helper.rb
module EndsHelper
end

app/views/ends/_form.html.erb
<%= form_with(model: end, local: true) do |form| %>
  <% if end.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(end.errors.count, "error") %> prohibited this end from being saved:</h2>

      <ul>
      <% end.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.number_field :product_id, id: :end_product_id %>
  </div>

  <div class="field">
    <%= form.label :product_page %>
    <%= form.number_field :product_page, id: :end_product_page %>
  </div>

  <div class="field">
    <%= form.label :position %>
    <%= form.number_field :position, id: :end_position %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ends/edit.html.erb
<h1>Editing End</h1>

<%= render 'form', end: @end %>

<%= link_to 'Show', @end %> |
<%= link_to 'Back', ends_path %>

app/views/ends/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Decathlon</h1>
<h2>Ends of series</h2>
<% if ! mobile? %>
  <table>
    <thead>
      <tr>
        <th>Product ID  </th>
        <th>Page of End of series </th>
        <th>Position on specific page  </th>
        <th>Image</th>
        <th>Family</th>
        <th colspan="5"></th>
      </tr>
    </thead>

    <tbody>
      <% @ends.each do |ends| %>
        <tr>
          <td><%= ends.product_id %></td>
          <td><%= ends.product_page %></td>
          <td><%= ends.position %></td>
          <td><%=image_tag("http://www.decathlon.pl#{ends.img}")%></td>
          <td><%= ends.family %></td>
          <td><%=link_to "Open the site", "https://www.decathlon.pl/C-394910-dobre-okazje/I-Page" + "#{ends.product_page}" + "_40", target: :_blank %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

<%else%>

  <table>
    <thead>
      <tr>
        <th>Product ID  </th>
        <th>Page of End of series </th>
        <th>Position on specific page  </th>
        <th>Image</th>
        <th colspan="4"></th>
      </tr>
    </thead>

    <tbody>
      <% @ends.each do |ends| %>
        <tr>
          <td><%= ends.product_id %></td>
          <td><%= ends.product_page %></td>
          <td><%= ends.position %></td>
          <td><%=image_tag("http://www.decathlon.pl#{ends.img}")%></td>
          <td><%=link_to "Open the site", "https://www.decathlon.pl/C-394910-dobre-okazje/I-Page" + "#{ends.product_page}" + "_40", target: :_blank %></td>
        </tr>
      <% end %>
    </tbody>
  </table>


<%end%>

<br>

app/views/ends/new.html.erb
<h1>New End</h1>

<%= render 'form', end: @end %>

<%= link_to 'Back', ends_path %>

app/views/ends/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @end.product_id %>
</p>

<p>
  <strong>Product page:</strong>
  <%= @end.product_page %>
</p>

<p>
  <strong>Position:</strong>
  <%= @end.position %>
</p>

<%= link_to 'Edit', edit_end_path(@end) %> |
<%= link_to 'Back', ends_path %>