config/routes.rb
Rails.application.routes.draw do
  get 'sessions/create'

  get 'sessions/destroy'

  get 'home/show'
  get 'data', to: 'analytics#data'
  get 'users/:id/edit', to: 'user#edit'
  post 'users/:id/edit', to: 'user#update' 
  get 'account_summaries', to: 'analytics#account_summaries'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get '/check_index' => "google_index#check_index"
  post '/check_index' => "google_index#response_index"
  get '/keywords' => "google_index#index"
  resources :sports

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]

  root to: "home#show"

 get "/koniec-serii" => 'ends#index'
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  get "/codeupdate" => "ends#codeupdate"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
require 'net/http'
require 'json'
class ApplicationRecord < ActiveRecord::Base
    require 'google/apis/analytics_v3'
  self.abstract_class = true
end

app/models/end.rb
class End < ApplicationRecord
end

app/models/google_index.rb
class GoogleIndex < ApplicationRecord
end

app/models/sport.rb
class Sport < ApplicationRecord
    has_many :user_sports
    has_many :users, through: :user_sports
    validates :name, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :user_sports
  has_many :sports, through: :user_sports
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.picture = auth.info.image
      user.refresh_token = auth.credentials.refresh_token
      #byebug
      user.save!
    end
  end
  
  def to_params
    {'refresh_token' => self.refresh_token,
    'client_id' => "915735438771-ee0msacribn2n52lqb8mge1p51pt7aii.apps.googleusercontent.com",
    'client_secret' => "LhRKxXqc6eRlGf5ixfSe7yNg",
    'grant_type' => 'refresh_token'}
  end
 
  def request_token_from_google
    url = URI("https://accounts.google.com/o/oauth2/token")
    byebug
    Net::HTTP.post_form(url, self.to_params)
  end
 
  def refresh!
    response = request_token_from_google
    data = JSON.parse(response.body)
    byebug
    self.oauth_token =  data['access_token']
    self.oauth_expires_at = Time.now + data['expires_in']
    self.save!
  end

  def expired?
    if self.oauth_expires_at.to_i < Time.now.to_i
      return true
    else
      return false
    end
  end
 
 private
 
  def fresh_token
    self.refresh! if self.expired?
    self.oauth_token
  end
 
end
  
  

app/models/user_sport.rb
class UserSport < ApplicationRecord
    belongs_to :user
    belongs_to :sport
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
end

app/controllers/ends_controller.rb
class EndsController < ApplicationController
  before_action :set_end, only: [:show, :edit, :update, :destroy]
  before_action :require_user

  # GET /ends
  # GET /ends.json
  def index
    @ends = End.all
    #UpdateCodeJob.perform_later
  end
  
  def response_index
     flash[:success] = "#{params[:name]}   #{params[:site_name]}"
     CheckIndexJob.perform_later(params[:name],params[:site_name])
     respond_to do |format|
      format.html { redirect_to root_path }
    end
  end
  
  def check_index
    
  end

  def codeupdate
    UpdateCodeJob.perform_later
    flash[:success] = "Wait 2 minutes and refresh the page"
    respond_to do |format|
      format.html { redirect_to root_path }
    end
  end

  # GET /ends/1
  # GET /ends/1.json
  def show
  end

  # GET /ends/new
  def new
    @end = End.new
  end

  # GET /ends/1/edit
  def edit
  end

  # POST /ends
  # POST /ends.json
  def create
    @end = End.new(end_params)

    respond_to do |format|
      if @end.save
        format.html { redirect_to @end, notice: 'End was successfully created.' }
        format.json { render :show, status: :created, location: @end }
      else
        format.html { render :new }
        format.json { render json: @end.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ends/1
  # PATCH/PUT /ends/1.json
  def update
    respond_to do |format|
      if @end.update(end_params)
        format.html { redirect_to @end, notice: 'End was successfully updated.' }
        format.json { render :show, status: :ok, location: @end }
      else
        format.html { render :edit }
        format.json { render json: @end.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ends/1
  # DELETE /ends/1.json
  def destroy
    @end.destroy
    respond_to do |format|
      format.html { redirect_to ends_url, notice: 'End was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_end
      @end = End.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def end_params
      params.require(:end).permit(:product_id, :product_page, :position)
    end
    
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
    
    def index
        @sports = current_user.sports
    end
    
end

app/controllers/user_controller.rb
class UserController < ApplicationController
    before_action :set_user, only: [:edit, :update, :show]
    
    
    def edit
        @user = User.find(params[:id])
        
    end
    
    def update
        if @user.update(user_params)
            flash[:success] = "Subskrypcje zaktualizowane"
            respond_to do |format|
            format.html { redirect_to root_path }
            end
        else
            render 'edit'
        end
    end
    
    
    private
    
    def set_user
        @user = current_user
    end
    
    def user_params
        params.require(:user).permit(:name,sport_ids: []) #sports_ids[]
    end
end

app/helpers/analytics_helper.rb
module AnalyticsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/ends_helper.rb
module EndsHelper
end

app/helpers/google_index_helper.rb
module GoogleIndexHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/_navigation.html.erb
<ul class="nav nav-pills">
  <li role="presentation" class="active"><a href="#">Yellow price</a></li>
  <li role="presentation"><a href="#">Sticker</a></li>
  <li role="presentation"><a href="#">Messages</a></li>
</ul>

app/views/layouts/app2.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Seriesend</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navigation' %>  
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Google Tag Manager -->
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-KXR3384');</script>
    <!-- End Google Tag Manager -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Seriesend" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>


    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>
    <!-- Google Tag Manager (noscript) -->
    <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-KXR3384"
    height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <!-- End Google Tag Manager (noscript) -->

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Seriesend</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <% if request.env['PATH_INFO'] == "/koniec-serii" %>
            <li><%= link_to "Refresh", codeupdate_path, class: "btn btn-warning" %></li>
            <%end%>
            <% if current_user %>
            <li><%= link_to "Dodaj sporty", "/users/#{current_user.id}/edit"  %></li>
            <% end %>
            <li><%= link_to "Końce serii", "/koniec-serii"  %></li>
            <li><%= link_to "Sprawdź SEO", "/check_index"  %></li>
            <li><%= link_to "Historia SEO", "/keywords"  %></li>
      <% if current_user %>
        <li><%= link_to "Sign out", signout_path, id: "sign_out" %></li>
        <li><p id="zalogowany">Zalogowany jako <strong><%= current_user.name %></strong>!</p></li>
      <% else %>
        <li><%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %></li>
      <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
              
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Patryk Dąbrowski</p>
      </footer>
      

    </div> <!-- /container -->

  </body>
</html>